# app/core/constants.py
"""Business rules and limits for LookOut"""

# User Limits
MAX_WORKSPACES_PER_USER = 5
MAX_ENDPOINTS_PER_WORKSPACE = 7
MAX_TOTAL_ENDPOINTS_PER_USER = 35

# Endpoint Configuration Limits
MIN_CHECK_FREQUENCY_SECONDS = 300  # 5 minutes
MAX_CHECK_FREQUENCY_SECONDS = 3600  # 1 hour
MIN_TIMEOUT_SECONDS = 5
MAX_TIMEOUT_SECONDS = 120
MAX_URL_LENGTH = 500
MAX_HEADERS_COUNT = 20
MAX_HEADER_KEY_LENGTH = 100
MAX_HEADER_VALUE_LENGTH = 1000
MAX_BODY_LENGTH = 10000  # 10KB

# Workspace Limits
MIN_WORKSPACE_NAME_LENGTH = 1
MAX_WORKSPACE_NAME_LENGTH = 100
MAX_WORKSPACE_DESCRIPTION_LENGTH = 500

# Endpoint Limits  
MIN_ENDPOINT_NAME_LENGTH = 1
MAX_ENDPOINT_NAME_LENGTH = 100

# Allowed HTTP Methods
ALLOWED_HTTP_METHODS = ["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS", "PATCH"]

# Status Code Ranges
MIN_EXPECTED_STATUS_CODE = 100
MAX_EXPECTED_STATUS_CODE = 599